### ISSUE TITLE
Fails in strict mode

### ISSUE THREAD

**Issue by k-funk** [difelice/ejs-loader#12]
`Module build failed: SyntaxError: <path> 'with' in strict mode`
lodash's template uses `with`.

Is there any workaround? I'm surprised that I'm the only one with this issue.

```
{
    test: /\.ejs/,
    loader: 'ejs-loader',
    include: path.join(sourceDir, '_assets', 'javascripts', 'templates')
}
```

Using `import 'template_name.ejs'` to include it.

**Comment by okonet** [comment]
I'm not using this module ATM so can't verify it. Can you create a repo where this is reproducible? Or even better, submit a fix in a PR. Thanks!

**Comment by topher515** [comment]
This happens for me as well. It occurs when you don't specify a `variable` in your `query`.

**Comment by dhaval-lila** [comment]
this happens with me as well. I am using ejs-loader for jest testing tranformation

**Comment by AtofStryker** [comment]
This is a fundamental issue with `lodash`'s template compiler. Lodash does not plan to resolve the issue, as seen on https://github.com/lodash/lodash/issues/3709#issuecomment-375898111. If you wish to use ES6 strict mode with `ejs-loader`, you can pass the new `exportAsESM` option into the loader. This will work fine as long as `variable` is provided in the options
