### ISSUE TITLE
"not a loader" error in webpack 2.1.0-beta.27

### ISSUE THREAD

**Issue by Birowsky** [difelice/ejs-loader#16]
Does this mean that the latest webpack is not supported?

The message:

> 
> throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
> 			^
> 
> Error: Module '/path/to/loader/ejs' is not a loader (must have normal or pitch function)

**Comment by okonet** [comment]
Probably. Did they change loader format or something? I'm not sure about it.

**Comment by Birowsky** [comment]
Sorry, no idea. I'm just a consumer here.

**Comment by okonet** [comment]
Yeah, me too. I wrote it for my project and it has been using Webpack 1.x. If you find an issue, please file a PR.
