### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by pldg** [difelice/ejs-loader#33]
`ejs-loader` use an old version of `lodash` which has [1 low severity vulnerability](https://nodesecurity.io/advisories/577), `lodash` should be updated to >=4.17.5

**Comment by jkumara** [comment]
This was fixed in pull request https://github.com/okonet/ejs-loader/pull/32 Any chance it could be merged and released soon?

**Comment by cjwillis809** [comment]
I'm seeing this same vulnerability in one of my projects. Any update on when #32 might be merged?

**Comment by Oleh-Matviiv** [comment]
Why can't we make it without lodash at all ?

**Comment by silentsakky** [comment]
Now we got one moderate vulnerability also 

Moderate        Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.11                                                     
                                                                                
  Dependency of   ejs-loader                                                    
                                                                                
  Path            ejs-loader > lodash                                           
                                                                                
  More info       https://npmjs.com/advisories/782

**Comment by difelice** [comment]
Fixed via https://github.com/difelice/ejs-loader/pull/35
