### ISSUE TITLE
Use esModule instead of exportAsESM

### ISSUE THREAD

**Issue by dmnsgn** [difelice/ejs-loader#44]
I see https://github.com/difelice/ejs-loader/pull/42 adds support for ES modules.
@AtofStryker @difelice what do you think of using `esModule` instead of `exportAsESM`?

Just to be coherent with other loaders such as:
- https://webpack.js.org/loaders/file-loader/#esmodule
- https://webpack.js.org/loaders/raw-loader/#esmodule
- https://webpack.js.org/loaders/url-loader/#esmodule
- https://webpack.js.org/loaders/json5-loader/#esmodule
- https://webpack.js.org/plugins/mini-css-extract-plugin/#esmodule

**Comment by difelice** [comment]
That makes sense, @AtofStryker will that work for you? Thanks.

**Comment by AtofStryker** [comment]
@difelice I don't see why not :smile: . We should definitely be consistent with the other loaders.

**Comment by AtofStryker** [comment]
@dmnsgn I can open a quick PR to support this if that is ok with you?

**Comment by AtofStryker** [comment]
Also, while on the issue of consistency, it looks like all of these loaders set `esModule` as `true` by default. I am for setting this behavior to `true` by default. How does that sound @difelice @dmnsgn?

**Comment by AtofStryker** [comment]
https://github.com/difelice/ejs-loader/pull/45 is opened to address this issue
